/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details take a look at the Scala plugin chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.3/userguide/scala_plugin.html
 */

description = "Gradoop Spark Common"

dependencies {
    "implementation"("com.github.s1ck:gdl:${Versions.gdl}")
}
